# Generated by Django 5.1.2 on 2024-10-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_laptop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
