# Generated by Django 5.1.2 on 2024-10-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_laptop_processor_laptop_ram_laptop_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
