# Generated by Django 5.1.2 on 2024-10-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_laptop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]

def copy_price_to_old_price(apps,schema_editor):
    Laptop = apps.get_model('store','Laptop')
    for laptop in Laptop.objects.all():
        laptop.old_price = laptop.price
        laptop.save()

