# Generated by Django 5.2.1 on 2025-05-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_laptop_old_price_laptop_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
