# Generated by Django 5.2.1 on 2025-05-26 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='store.category'),
        ),
    ]
