# Generated by Django 5.2.1 on 2025-05-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_laptop_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptop',
            new_name='Product',
        ),
    ]
